package my.jhipster.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserGroupAllPropertiesEquals(UserGroup expected, UserGroup actual) {
        assertUserGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertUserGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserGroupAllUpdatablePropertiesEquals(UserGroup expected, UserGroup actual) {
        assertUserGroupUpdatableFieldsEquals(expected, actual);
        assertUserGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserGroupAutoGeneratedPropertiesEquals(UserGroup expected, UserGroup actual) {
        assertThat(expected)
            .as("Verify UserGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserGroupUpdatableFieldsEquals(UserGroup expected, UserGroup actual) {
        assertThat(expected)
            .as("Verify UserGroup relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserGroupUpdatableRelationshipsEquals(UserGroup expected, UserGroup actual) {
        assertThat(expected)
            .as("Verify UserGroup relationships")
            .satisfies(e -> assertThat(e.getAppUser()).as("check appUser").isEqualTo(actual.getAppUser()));
    }
}
